//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlacowkaOswiatowa.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlacowkaOswiatowa.Domain.Resources.BaseResources", typeof(BaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj w aplikacji Placówka Oświatowa!.
        /// </summary>
        public static string DefaultStatusMessage {
            get {
                return ResourceManager.GetString("DefaultStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj pracownika.
        /// </summary>
        public static string DodajPracownika {
            get {
                return ResourceManager.GetString("DodajPracownika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj ucznia.
        /// </summary>
        public static string DodajUcznia {
            get {
                return ResourceManager.GetString("DodajUcznia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja pracownika.
        /// </summary>
        public static string EdycjaPracownika {
            get {
                return ResourceManager.GetString("EdycjaPracownika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja ucznia.
        /// </summary>
        public static string EdycjaUcznia {
            get {
                return ResourceManager.GetString("EdycjaUcznia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura.
        /// </summary>
        public static string Faktura {
            get {
                return ResourceManager.GetString("Faktura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktury.
        /// </summary>
        public static string Faktury {
            get {
                return ResourceManager.GetString("Faktury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa umowa.
        /// </summary>
        public static string NowaUmowa {
            get {
                return ResourceManager.GetString("NowaUmowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy Pracownik.
        /// </summary>
        public static string NowyPracownik {
            get {
                return ResourceManager.GetString("NowyPracownik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy Uczeń.
        /// </summary>
        public static string NowyUczen {
            get {
                return ResourceManager.GetString("NowyUczen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string SaveItem {
            get {
                return ResourceManager.GetString("SaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towar.
        /// </summary>
        public static string Towar {
            get {
                return ResourceManager.GetString("Towar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urlop Pracownika.
        /// </summary>
        public static string UrlopPracownika {
            get {
                return ResourceManager.GetString("UrlopPracownika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszyscy Pracownicy.
        /// </summary>
        public static string WszyscyPracownicy {
            get {
                return ResourceManager.GetString("WszyscyPracownicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszyscy Uczniowie.
        /// </summary>
        public static string WszyscyUczniowie {
            get {
                return ResourceManager.GetString("WszyscyUczniowie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie Adresy.
        /// </summary>
        public static string WszystkieAdresy {
            get {
                return ResourceManager.GetString("WszystkieAdresy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie Oceny.
        /// </summary>
        public static string WszystkieOceny {
            get {
                return ResourceManager.GetString("WszystkieOceny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie Przedmioty.
        /// </summary>
        public static string WszystkiePrzedmioty {
            get {
                return ResourceManager.GetString("WszystkiePrzedmioty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie Stanowiska.
        /// </summary>
        public static string WszystkieStanowiska {
            get {
                return ResourceManager.GetString("WszystkieStanowiska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie Urlopy.
        /// </summary>
        public static string WszystkieUrlopy {
            get {
                return ResourceManager.GetString("WszystkieUrlopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarobki Pracownika.
        /// </summary>
        public static string ZarobkiPracownika {
            get {
                return ResourceManager.GetString("ZarobkiPracownika", resourceCulture);
            }
        }
    }
}
